### ISSUE TITLE
Shutdown OS without stopping VPN connection causes no network connectivity

### ISSUE THREAD

**Issue by hamm3l** [Jigsaw-Code/outline-apps#2442]
### Application

Outline Client

### Describe the bug

Failing to disconnect from the Outline VPN before shutting down your computer results in all network traffic being forced down the TUN adapter created by Outline, despite it leading to nowhere. The only way to work around this is to delete the IP and virtual TUN adapter:

`ip addr delete 10.0.85.5/32 dev outline-tun1`
`ip link delete outline-tun1`

Note that you cannot even reconnect to your Outline server either when in this broken state.

### Steps to reproduce

1. Connect to an Outline server.
2. Without disconnecting, shut down your computer.
3. Power back on.
4. Attempt to ping your default gateway on your local network, or a public IP address.
5. Observe that you cannot reach any IP addresses over any protocol.

### What did you expect to happen?

Be able to use the local network connection.

### What actually happened?

No network connectivity. Your device does receive an IP address from your local DHCP server, but any attempts to communicate over the network to your default gateway, other devices within the LAN, or any destination out to the internet seems to go nowhere. Attempting to perform a packet capture on the network adapter you are expecting to send traffic out of does not appear, as it is likely being forced down the TUN adapter.

### Outline Version

1.50.0 (483121)

### What operation system are you using?

Linux

### Operating System Version

Pop! OS 22.04 LTS

**Comment by sbruens** [comment]
Thanks for reporting this issue @hamm3l.

This could be a race condition or bug where the network manager did not remove the transient `outline-tun1` device. The workaround is indeed to delete the device. We need to see whether we can reproduce this issue.

**Comment by tuorqai** [comment]
If you're reading this issue trying to fix your broken network, try this:

```
sudo nmcli connection delete "Outline TUN Connection"
sudo nmcli device delete outline-tun1
sudo systemctl restart NetworkManager.service
```

For some reason "Outline TUN Connection" persists even after reboot. Probably a bug in Wifx/gonetworkmanager, but I'm not sure.

I would recommend not using Outline Client on Linux until this bug is fixed.

**Comment by alexander-potemkin** [comment]
[That](https://github.com/Jigsaw-Code/outline-apps/issues/2573#issuecomment-3183700133) looks related

**Comment by psevdoworld** [comment]
> I would recommend not using Outline Client on Linux until this bug is fixed.

I stopped using it for same exact reason and it took me week to arrive at this exact solution on Linux mint 22. Same issue was on windows 10 solved by completely resetting all network settings.

**Comment by Vitaly-Vyunov** [comment]
Hi, how can I restore my network setting after this issue occurred on my pc? I was able to delete the client app, but outline-tun1 still persists and nothing helps. Deleting device and link doesn't work.

**Comment by antongus** [comment]
> I stopped using it for same exact reason and it took me week to arrive at this exact solution on Linux mint 22. Same issue was on windows 10 solved by completely resetting all network settings.

What app you are using instead?
